# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  # For Rails 7 and newer:
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *connection
  database: app_db

test:
  <<: *connection
  database: rails_test
